var appConstants = {
  FORM_CLICKED: "FORM_CLICKED",
  PHYSICAL_ACTIVITY_MIN: "PHYSICAL_ACTIVITY_MIN",
  PHYSICAL_ACTIVITY_MID: "PHYSICAL_ACTIVITY_MID",
  PHYSICAL_ACTIVITY_MAX: "PHYSICAL_ACTIVITY_MAX",
  AGE_OVER_21: "AGE_OVER_21",
  AGE_UNDER_21: "AGE_UNDER_21",
  COST_FREE: "COST_FREE",
  COST_FIFTEEN: "COST_FIFTEEN",
  COST_FORTY: "COST_FORTY",
  COST_SEVENTYFIVE: "COST_SEVENTYFIVE",
  COST_SKY: "COST_SKY",
  BOWLING: "BOWLING",
  PADDLING: "PADDLING",
  KAYAKING: "KAYAKING",
  BILLIARDS: "BILLIARDS",
  ADD_LAT: "ADD_LAT",
  ADD_LNG: "ADD_LNG"
};

module.exports = appConstants;